import type { RefObject } from 'react'
import type { ToastTone } from '../app-shell/useMobileAppModel'
import type { AppState } from '../app-shell/useAppState'
import type { useMobileShelfModel } from '../library-workspace/useMobileShelfModel'
import type { SortMode } from '../library-workspace/libraryCore'
import { useAcquireWorkspaceViewModel } from './useAcquireWorkspaceViewModel'
import { useMobileAcquireControllerModel } from './useAcquireWorkspaceController'
import type { ShelfBook } from '../mobileStore'
import type { RvAgentSuccessTarget } from './acquireTypes'

type ShowToast = (tone: ToastTone, text: string) => void
type ShowCgsStatusToast = (status: Record<string, unknown> | null) => void
type ShelfModel = ReturnType<typeof useMobileShelfModel>

type MobileAcquireModelDeps = {
  cgsStatusToastKeyRef: RefObject<string>
  closeDoujinTagPanel: ShelfModel['closeDoujinTagPanel']
  openCgsTagPanel: ShelfModel['openCgsTagPanel']
  openRvAgentLlmConfig: () => void
  openSuccessTarget: (target: RvAgentSuccessTarget) => Promise<void> | void
  refreshLibrary: (url?: string, nextSort?: SortMode, resetPage?: boolean, showLoading?: boolean, sync?: boolean) => Promise<ShelfBook[]>
  selectCgsSearchCandidate: ShelfModel['selectCgsSearchCandidate']
  selectDoujinTag: ShelfModel['selectDoujinTag']
  show: ShowToast
  showCgsStatusToast: ShowCgsStatusToast
}

export function useMobileAcquireModel(appState: AppState, deps: MobileAcquireModelDeps) {
  const {
    backendUrl,
    busy,
    cgsBooks,
    cgsConfig,
    cgsConfigBusy,
    cgsConfigDraft,
    cgsConnection,
    cgsGateFlight,
    cgsGateLoadingMode,
    cgsGatePhase,
    cgsHeadGateFlight,
    chapterPanelBookKey,
    cgsManualGateRef,
    cgsAttachedBook,
    cgsAttachedBookList,
    rvAgentComposerRef,
    rvAgentExpandedToolId,
    rvAgentGateRef,
    rvAgentHistoryOpen,
    rvAgentLibrarySyncing,
    cgsMcpLlmDraft,
    rvAgentModelHelpOpen,
    rvAgentPreferenceOpen,
    rvAgentPreferenceState,
    rvAgentPrompt,
    rvAgentPromptHistory,
    rvAgentRunning,
    rvAgentScrollRef,
    rvAgentTimeline,
    cgsModeSwap,
    cgsSearchBookInfo,
    cgsSessionId,
    cgsCurrentPage,
    cgsStatus,
    cgsSubmitStatusInfoOpen,
    cgsSubmitStatusInfoText,
    cgsSubmitPosition,
    cgsWorkspaceMode,
    comicConfig,
    comicPathDraft,
    doujinTagPanel,
    episodeLoadByBook,
    episodesByBook,
    keyword,
    selectedEpisodeKeysByBook,
    selectedKeys,
    selectedSite,
    sites,
    view,
    setCgsConfigDraft,
    setRvAgentExpandedToolId,
    setRvAgentHistoryOpen,
    setCgsMcpLlmDraft,
    setRvAgentModelHelpOpen,
    setRvAgentPreferenceOpen,
    setRvAgentPreferenceState,
    setRvAgentPrompt,
    setCgsSearchBookInfo,
    setKeyword,
    setSelectedEpisodeKeysByBook,
    setSelectedKeys,
    setSelectedSite,
    rvAgentRepair,
  } = appState

  const cgsGateBusy = cgsGatePhase === 'loading' || cgsGatePhase === 'flying'
  const cgsModeSwapBusy = Boolean(cgsModeSwap)
  const cgsBookshelfPath = comicPathDraft || comicConfig?.path || ''

  const {
    clearBookEpisodes,
    closeCgsSubmitStatusInfo,
    closeChapterPanel,
    completeCgsGateFlight,
    dismissRvAgentRepair,
    detachAttachedBook,
    finishCgsSubmitDrag,
    handleRvAgentPromptKeyDown,
    moveCgsSubmitDrag,
    openCgsSubmitStatusInfo,
    openChapterPanel,
    removeRvAgentHistoryPrompt,
    retryBookEpisodes,
    repairCgsMissingPages,
    retryRvAgentRepair,
    runCgsGateLoad,
    saveRvAgentLlmConfig,
    searchCgs,
    selectAllBookEpisodes,
    selectFirstBookEpisodes,
    selectLatestBookEpisodes,
    sendRvAgentPrompt,
    startRvAgentNewSession,
    startCgsSubmitDrag,
    stopRvAgentPrompt,
    submitCgs,
    turnCgsPage,
    switchCgsWorkspaceMode,
    syncCgsSavePathFromBookshelf,
    toggleEpisodeKey,
    updateCgsConfig,
  } = useMobileAcquireControllerModel(appState, {
    cgsBookshelfPath,
    cgsGateBusy,
    cgsStatusToastKeyRef: deps.cgsStatusToastKeyRef,
    refreshLibrary: deps.refreshLibrary,
    show: deps.show,
    showCgsStatusToast: deps.showCgsStatusToast,
  })

  const acquireWorkspace = useAcquireWorkspaceViewModel({
    backendUrl,
    bookshelfPath: cgsBookshelfPath,
    busy,
    cgsBooks,
    cgsConfig,
    cgsConfigBusy,
    cgsConfigDraft,
    cgsConnection,
    cgsGateBusy,
    cgsGateFlight,
    cgsGateLoadingMode,
    cgsGatePhase,
    cgsHeadGateFlight,
    chapterPanelBookKey,
    cgsAttachedBook,
    cgsAttachedBookList,
    rvAgentExpandedToolId,
    rvAgentHistoryOpen,
    rvAgentLibrarySyncing,
    cgsMcpLlmDraft,
    rvAgentModelHelpOpen,
    rvAgentPreferenceOpen,
    rvAgentPreferenceState,
    rvAgentPrompt,
    rvAgentPromptHistory,
    rvAgentRunning,
    rvAgentTimeline,
    cgsModeSwapBusy,
    cgsSearchBookInfo,
    cgsSessionId,
    cgsCurrentPage,
    cgsStatus,
    cgsSubmitStatusInfoOpen,
    cgsSubmitStatusInfoText,
    cgsSubmitPosition,
    cgsWorkspaceMode,
    doujinTagPanel,
    episodeLoadByBook,
    episodesByBook,
    keyword,
    selectedEpisodeKeysByBook,
    selectedKeys,
    selectedSite,
    sites,
    toastWarnIconSrc: appState.skinAssets.toastWarnIconSrc,
    toastSuccessIconSrc: appState.skinAssets.toastSuccessIconSrc,
    view,
    cgsManualGateRef,
    rvAgentComposerRef,
    rvAgentGateRef,
    rvAgentScrollRef,
    clearBookEpisodes,
    clearSelection: () => {
      setSelectedKeys([])
      setSelectedEpisodeKeysByBook({})
    },
    closeChapterPanel,
    closeCgsSubmitStatusInfo,
    closeDoujinTagPanel: deps.closeDoujinTagPanel,
    closeSettingsDrawer: () => appState.setDrawerOpen(false),
    completeCgsGateFlight,
    finishCgsSubmitDrag,
    handleRvAgentPromptKeyDown,
    moveCgsSubmitDrag,
    openCgsSubmitStatusInfo,
    openChapterPanel,
    openCgsTagPanel: deps.openCgsTagPanel,
    openSuccessTarget: deps.openSuccessTarget,
    removeRvAgentHistoryPrompt,
    retryBookEpisodes,
    repairCgsMissingPages,
    runCgsGateLoad,
    saveRvAgentLlmConfig,
    searchCgs,
    selectAllBookEpisodes,
    selectCgsSearchCandidate: deps.selectCgsSearchCandidate,
    selectDoujinTag: deps.selectDoujinTag,
    selectFirstBookEpisodes,
    selectLatestBookEpisodes,
    sendRvAgentPrompt,
    startRvAgentNewSession,
    startCgsSubmitDrag,
    stopRvAgentPrompt,
    submitCgs,
    turnCgsPage,
    syncCgsSavePathFromBookshelf,
    updateCgsConfig,
    setCgsConfigDraft,
    setRvAgentExpandedToolId,
    setRvAgentHistoryOpen,
    setCgsMcpLlmDraft,
    setRvAgentModelHelpOpen,
    setRvAgentPreferenceOpen,
    setRvAgentPreferenceState,
    setRvAgentPrompt,
    setCgsSearchBookInfo,
    setKeyword,
    setSelectedKeys,
    setSelectedSite,
    rvAgentRepair,
    dismissRvAgentRepair,
    detachAttachedBook,
    retryRvAgentRepair,
    openRvAgentLlmConfig: deps.openRvAgentLlmConfig,
    toggleEpisodeKey,
  })

  return {
    acquireWorkspace,
    cgsGateBusy,
    switchCgsWorkspaceMode,
  }
}
