skinBaseUrl: https://img-cgs.101114105.xyz/file/rv/skin

skin:
  default:
    _act:
      edge: [assets/skin.d/default/edge_effect.gif, 600]
      menu: [assets/skin.d/default/menu_effect.gif, 500]
    edge: 1781365855145_edge.png
    menu: 1781444636248_menu-strip.png
    settings_bg: 1781363766171_settings-bottom.gif
